### ISSUE TITLE
HDR视频文件转换SDR视频文件

### ISSUE THREAD

**Issue by XiakeBen** [JonaNorman/HDRSample#3]
怎么利用android的硬件编解码，把HDR视频转化SDR后，编码生成一个SDR的视频文件，能不能提供一些思路和方案，谢谢
目前我使用FFMPEG来做转化，速度太慢了

**Comment by JonaNorman** [comment]
正常使用mediacodec编码就行，中间加个hdr转sdr的shader处理，shader可以直接用demo里面，如果只是想解决问题，对于色域和tonemap一头雾水，可以用直接用[CubeLutVideoTransform](https://github.com/JonaNorman/HDRSample/blob/main/sample/src/main/java/com/norman/android/hdrsample/transform/CubeLutVideoTransform.java)读取对应的lut文件加载效果就行
